server:
  port: 80  #服务器端口号
  servlet:
    context-path: /localfts  #服务器上下文路径
spring:
  servlet:
    multipart:
      max-file-size: 2GB  #上传最大文件大小
      max-request-size: 2GB  #上传最大请求大小
      #resolve-lazily: true
      #file-size-threshold: 0
localfts:
  root_path: D:\Users\Adam\Documents  #服务器根路径映射地址
  show_hidden: false  #是否显示隐藏文件和文件夹，同步影响索引行为
  zip:
    enabled: true  #文件夹压缩功能开关
    path: localfts_zip  #文件夹压缩文件存储路径，对根路径的相对路径
    delete_on_exit: true  #!!!退出服务器进程时是否清理压缩文件存储路径
    max-folder-size: 3GB  #限制压缩文件夹原文件夹的大小(超过此数值不能压缩)
    background-enabled: false  #后台压缩开关，不允许时关闭压缩管理页面(/compressFolder)时会结束正在进行的压缩任务
  log:
    file_path: log  #日志文件存储相对路径(相对进程工作目录，而非相对根路径)
    root_level: DEBUG  #日志默认级别
  upload:
    directory:
      pseudo-ua-contains: ["HuaweiBrowser/16.0.7.301 Mobile", "EdgiOS"]  #上传文件页面根据浏览器User-Agent标识和此字段对伪支持上传文件夹的浏览器不展示上传文件夹元素
  pseudo-unload-ua-contains: ["HuaweiBrowser/16.0.7.301 Mobile", "EdgiOS"]  #根据浏览器User-Agent和此字段对离开页面不触发页面卸载事件的浏览器进行提示
  mkdir:
    enabled: true  #创建文件夹功能开关
  search:
    enabled: true  #搜索功能开关
    mode: PLAIN #模式：PLAIN-直接搜索，INDEXED-索引搜索
    timeout: 30  #超时时间(秒)，建议配置超时时间，否则搜索任务可能会长时间不退出
    active-task-threshold-str: 0.5p  #活跃搜索任务阈值，格式为正整数或正数+p(代表乘以物理核心数)，不能超过物理核心数。默认值：物理核心数/2
    index-path: index-dir  #索引相对路径
    index-before-start: true #是否在启动Web服务器前创建索引
    use-existing-index: false  #是否使用已有的索引，不使用则在启动时删除已有索引并重新创建
    index-file-content:
      enabled: true  #!!是否对文件内容进行索引（索引耗时更长）
      max-string-length-memory-str: 20MB  #!!限制文件内容字符串所占据的最大内存空间，-1表示无限制。建议不超过20MB,对应10,485,760长度的字符串，值过大时既消耗内存也消耗CPU。
      try-read-all-files: false  #!!是否尝试读取所有类型的文件，影响性能
      default-encoding: UTF-8  #当无法检测文件编码时默认使用的编码格式
  test_language:
    Simplified_Chinese: true  #测试终端输出文字是否乱码(简体中文)